language: rust
rust: nightly
cache: cargo

services:
  - docker
  
env:
  - diesel-cli ='docker run --rm \
                    -v "$PWD:/volume" \
                    -w /volume \
                    --network="rocket-server_default" \
                    -it ryanchristian4427/diesel-cli migration run'

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - docker-compose -f rocket-server/docker-compose.yml up --build -d
  - diesel-cli migration run

script:
  - 'cargo check --manifest-path=rocket-server/Cargo.toml --verbose'
  - 'cargo test --manifest-path=rocket-server/Cargo.toml --verbose'

