language: rust
rust: nightly
cache: cargo

services:
  - docker
  
env:
  - diesel-cli ='docker run --rm \
                    -v "$PWD:/volume" \
                    -w /volume \
                    --network="rocket-server_default" \
                    -it ryanchristian4427/diesel-cli migration run'

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
    
before_script:
  - docker --version
  - docker-compose -f rocket-server/docker-compose.yml up --build -d
  - diesel-cli migration run

script:
  - 'cargo check --manifest-path=rocket-server/Cargo.toml --verbose'
  - 'cargo test --manifest-path=rocket-server/Cargo.toml --verbose'

