language: rust
rust: nightly
cache: cargo

services:
  - docker

#env:
#  global:
#    - diesel-cli = 'docker run --rm -v "$PWD:/volume" -w /volume --network="rocket-server_default" -it ryanchristian4427/diesel-cli migration run'

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
    
before_script:
  - sudo /etc/init.d/postgresql stop
  - cd rocket-server
  - docker-compose up --build -d
  - docker run --rm -v "$PWD:/volume" -w /volume --network="rocket-server_default" -it ryanchristian4427/diesel-cli migration run

script:
  - 'cargo check --verbose'
  - 'cargo test --verbose'

