language: rust
rust: nightly
dist: xenial
sudo: false

services:
  - docker

install:
  - cd rocket-server
  - docker-compose up --build -d
  - docker run --rm -v "$PWD:/volume" -w /volume --network="rocket-server_default" -it ryanchristian4427/diesel-cli migration run


jobs:
  include:
    - stage: "Rust"
      name: "Cargo Check"
      script: "cargo check"
    - name: "Cargo Test"
      script: "cargo test"
