dist: xenial

services:
  - docker

jobs:
  include:
    - language: rust
      rust: nightly
      cache: cargo
      install:
        - cd packages/api
        - docker-compose up --build -d
        - docker run --rm -v "$PWD:/volume" -w /volume --network="api_default" -it ryanchristian4427/diesel-cli migration run
      script:
        - cargo check
        - cargo test
    - language: node_js
      node_js: 14.x
      cache: yarn
      install:
        - yarn
      script:
        - yarn build
