language: rust
rust: nightly
cache: cargo

services:
  - docker
  
env:
  - diesel-cli ='docker run --rm \
                    -v "$PWD:/volume" \
                    -w /volume \
                    --network="rocket-server_default" \
                    -it ryanchristian4427/diesel-cli migration run'
  
before_script:
  - docker-compose up --build -d
  - diesel-cli migration run

script:
  - 'cargo check --verbose'
  - 'cargo test --verbose'

