language: rust
rust: nightly
cache: cargo
dist: xenial

services:
  - docker
    
before_script:
  - cd rocket-server
  - docker-compose up --build -d
  - docker run --rm -v "$PWD:/volume" -w /volume --network="rocket-server_default" -it ryanchristian4427/diesel-cli migration run


jobs:
  include:
    - stage: "Rust"
      name: "Cargo Build"
      script: "cargo build"
    - name: "Cargo Test"
      script: "cargo test"