language: rust
rust: nightly
dist: xenial
sudo: false

cache: cargo

services:
  - docker

env:
  # Disable rustc info cache because it causes .rustc_info.json to keep
  # changing which destablize the cache.
  - 'CARGO_CACHE_RUSTC_INFO=0'
    
install:
  - cd rocket-server
  - docker-compose up --build -d
  - docker run --rm -v "$PWD:/volume" -w /volume --network="rocket-server_default" -it ryanchristian4427/diesel-cli migration run


jobs:
  include:
    - stage: "Rust"
      name: "Cargo Check"
      script: "cargo check"
    - name: "Cargo Test"
      script: "cargo test"

before_cache:
  - rm -rf target/debug/incremental
  - rm -rf target/debug/{build,.fingerprint,deps}/tempest-*
  - rm -rf target/debug/deps/libtempest-*
  - rm -rf target/debug/tempest-*
  - cargo clean -p tempest

