name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: cargo check --manifest-path=rocket-server/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path=rocket-server/Cargo.toml --verbose
